version: '3.0'

services:
    ###########################################################################
    # Flow Services
    ###########################################################################
    app:
        image: docker.convisoappsec.com/flow-app:2
        restart: always
        env_file:
            -  "app/common_configuration.env"
        environment:
            RAILS_LOG_TO_STDOUT: 1
            SECRET_KEY_BASE: "${APP_SECRET_KEY_BASE}"
        volumes:
            - app-tmp:/app/tmp
            - app-storage:/app/storage
        networks:
            - flow-onpremise-backend

        depends_on:
            - db
            - redis
        healthcheck:
            test: "curl --fail http://localhost:9292/portal_users/sign_in"
            interval: 30s
            timeout: 10s
            retries: 10

    app-worker:
        image: docker.convisoappsec.com/flow-app:2
        restart: always
        env_file:
            -  "app/common_configuration.env"
        environment:
            SECRET_KEY_BASE: "${APP_SECRET_KEY_BASE}"
        command: "start_sidekiq"
        volumes:
            - app-tmp:/app/tmp
            - app-storage:/app/storage
        networks:
            - flow-onpremise-backend
        depends_on:
            - db
            - redis

    magister-api:
        image: docker.convisoappsec.com/magister-api
        restart: always
        environment:
            RAILS_LOG_TO_STDOUT: 1
        env_file:
            - ./magister/config.env

        volumes:
            - "magister-api-public-system:/app/public/system"
            - "magister-api-non-public-system:/app/non-public/system"
            - "magister-api-log:/app/log"
        networks:
            - flow-onpremise-backend
        depends_on:
            - magister-db
            - redis
            - minio
        healthcheck:
            test: "curl --fail http://localhost:3000"
            interval: 30s
            timeout: 10s
            retries: 10


    ###########################################################################
    # Infrastructure Services
    ###########################################################################
    web:
        image: docker.convisoappsec.com/flow-web
        restart: always
        ports:
            - "443:443"
        networks:
            flow-onpremise-frontend:
                ipv4_address: "${WEBSERVER_STATIC_IP}"
            flow-onpremise-backend:
        volumes:
            - ./web/etc/nginx/nginx.conf:/etc/nginx/nginx.conf

        depends_on:
           - app

    db:
        image: docker.convisoappsec.com/mysql-server
        restart: always
        env_file:
            -  "db/config.env"
        volumes:
            - "db:/var/lib/mysql"
        networks:
            - flow-onpremise-backend

    magister-db:
        image: docker.convisoappsec.com/mysql-server
        restart: always
        env_file:
            -  "magister-db/config.env"
        volumes:
            - "magister-db-data:/var/lib/mysql"
        networks:
            - flow-onpremise-backend

    redis:
        image: docker.convisoappsec.com/redis
        restart: always
        command: redis-server
        networks:
            - flow-onpremise-backend
        volumes:
            - 'redis:/data'

    minio:
        image: docker.convisoappsec.com/minio
        restart: always
        command: "server /data"
        env_file:
            - ./minio/config.env
        volumes:
            - "./minio/data:/data"
        networks:
            - flow-onpremise-backend

    registry:
        image: docker.convisoappsec.com/registry
        restart: always
        volumes:
            - registry-data:/var/lib/registry
        ports:
            - 5000:5000


volumes:
    registry-data:
    app-tmp:
    app-storage:
    db:
    redis:
    magister-api-public-system:
    magister-api-non-public-system:
    magister-api-log:
    magister-db-data:


networks:
    flow-onpremise-frontend:
        driver: bridge
        driver_opts:
            com.docker.network.enable_ipv6: "false"
        ipam:
          config:
              - subnet: "${WEBSERVER_SUBNET}"

    flow-onpremise-backend:
